import type { ReactNode } from 'react';
import { NativeModules, View } from 'react-native';
import Svg, { Path } from 'react-native-svg';
import { MAIN_GROUP_BBOX, taiwanIslands } from '@/data/taiwan-islands';

const EXPTECH_TILE_URL = 'https://static.lb.exptech.dev/api/v1/map/tiles/{z}/{x}/{y}.pbf';

// Self-hosted tile endpoints. When set, the app renders our own tiles instead of
  // ExpTech's; generated by scripts/map-tiles (source-layers land/county/town, so
  // no style change is needed). Terrain is optional and only added when configured.
const CUSTOM_TILE_URL = process.env.EXPO_PUBLIC_MAP_TILE_URL;
const TERRAIN_TILE_URL = process.env.EXPO_PUBLIC_MAP_TERRAIN_URL;
const BASE_TILE_URL = CUSTOM_TILE_URL || EXPTECH_TILE_URL;
// Our base tiles stop at z10 (MapLibre overzooms past it); ExpTech ships to z12.
const BASE_TILE_MAX_ZOOM = CUSTOM_TILE_URL ? 10 : 12;
const BASE_ATTRIBUTION = CUSTOM_TILE_URL
  ? 'Natural Earth · 內政部國土測繪中心'
  : 'ExpTechTW';

// World land is only tiled to z5. A separate vector source capped at z5 lets
// MapLibre overzoom it, so neighbouring countries stay visible past z5 while the
// county/town layers keep their full z10 detail from the uncapped source.
const LAND_SOURCE_MAX_ZOOM = 5;
const LAND_SOURCE_ID = CUSTOM_TILE_URL ? 'weathertas-map-land' : 'weathertas-map';

// Terrain DEM bounds (Taiwan + islets) and native zoom ceiling.
const TERRAIN_BOUNDS: [number, number, number, number] = [118.0, 21.8, 122.1, 25.4];
const TERRAIN_MAX_ZOOM = 12;

const TAIWAN_BOUNDS: [number, number, number, number] = [118.15, 21.87, 122.05, 25.32];
type MapBounds = [number, number, number, number];
type MapPadding = { top: number; right: number; bottom: number; left: number };

export interface MapViewport {
  zoom: number;
  bounds: MapBounds;
}

type MapLibreModule = typeof import('@maplibre/maplibre-react-native');

let mapLibreModule: MapLibreModule | null | undefined;

export function getMapLibreModule(): MapLibreModule | null {
  if (!NativeModules.MLRNCameraModule) return null;
  if (mapLibreModule !== undefined) return mapLibreModule;

  try {
    // MapLibre is not bundled into Expo Go. Requiring it only after checking the
    // native module keeps Expo Go previews from crashing at startup.
    mapLibreModule = require('@maplibre/maplibre-react-native') as MapLibreModule;
  } catch {
    mapLibreModule = null;
  }

  return mapLibreModule;
}

const mapStyle = {
  version: 8,
  glyphs: 'https://demotiles.maplibre.org/font/{fontstack}/{range}.pbf',
  sources: {
    'weathertas-map': {
      type: 'vector',
      tiles: [BASE_TILE_URL],
      minzoom: 0,
      maxzoom: BASE_TILE_MAX_ZOOM,
      attribution: BASE_ATTRIBUTION,
    },
    ...(CUSTOM_TILE_URL
      ? {
          'weathertas-map-land': {
            type: 'vector',
            tiles: [BASE_TILE_URL],
            minzoom: 0,
            maxzoom: LAND_SOURCE_MAX_ZOOM,
            attribution: BASE_ATTRIBUTION,
          },
        }
      : {}),
    ...(TERRAIN_TILE_URL
      ? {
          terrain: {
            type: 'raster-dem',
            tiles: [TERRAIN_TILE_URL],
            encoding: 'mapbox',
            tileSize: 256,
            minzoom: 0,
            maxzoom: TERRAIN_MAX_ZOOM,
            bounds: TERRAIN_BOUNDS,
          },
        }
      : {}),
  },
  layers: [
    { id: 'background', type: 'background', paint: { 'background-color': '#E8F0F8' } },
    {
      id: 'land', type: 'fill', source: LAND_SOURCE_ID, 'source-layer': 'land',
      paint: { 'fill-color': '#DCE6EF' },
    },
    {
      id: 'county-fill', type: 'fill', source: 'weathertas-map', 'source-layer': 'county',
      paint: { 'fill-color': '#DCE6EF' },
    },
    {
      id: 'town-fill', type: 'fill', source: 'weathertas-map', 'source-layer': 'town',
      paint: { 'fill-color': '#DCE6EF' },
    },
    ...(TERRAIN_TILE_URL
      ? [
          {
            id: 'terrain-hillshade',
            type: 'hillshade',
            source: 'terrain',
            paint: {
              'hillshade-illumination-direction': 335,
              'hillshade-exaggeration': 0.3,
            },
          },
        ]
      : []),
    {
      id: 'town-outline', type: 'line', source: 'weathertas-map', 'source-layer': 'town', minzoom: 7.5,
      paint: {
        'line-color': '#8AA0B3',
        'line-width': 0.65,
        'line-opacity': ['interpolate', ['linear'], ['zoom'], 7.5, 0, 8.25, 0.58],
      },
    },
    {
      id: 'county-outline', type: 'line', source: 'weathertas-map', 'source-layer': 'county',
      paint: {
        'line-color': '#607C95',
        'line-width': ['interpolate', ['linear'], ['zoom'], 4, 0.7, 11, 1.25],
        'line-opacity': 0.82,
      },
    },
  ],
} as import('@maplibre/maplibre-react-native').StyleSpecification;

interface TaiwanMapProps {
  allowTap?: boolean;
  children?: ReactNode;
  initialBounds?: MapBounds;
  initialPadding?: MapPadding;
  onRegionDidChange?: (viewport: MapViewport) => void;
}

export function TaiwanMap({ children, initialBounds = TAIWAN_BOUNDS, initialPadding = { top: 24, right: 20, bottom: 24, left: 20 }, onRegionDidChange }: TaiwanMapProps) {
  const mapLibre = getMapLibreModule();

  if (!mapLibre) {
    return <TaiwanMapFallback />;
  }

  const { Camera, Map } = mapLibre;

  return (
    <Map
      style={{ flex: 1 }}
      mapStyle={mapStyle}
      preferredFramesPerSecond={60}
      androidView="surface"
      touchRotate={false}
      touchPitch={false}
      compass={false}
      scaleBar={false}
      logo={false}
      // The attribution button would sit under the bottom navigation bar, so it
      // is suppressed; source credits move to the settings licences page later.
      attribution={false}
      onRegionDidChange={(event) => onRegionDidChange?.({
        zoom: event.nativeEvent.zoom,
        bounds: event.nativeEvent.bounds,
      })}
    >
      <Camera
        minZoom={4}
        maxZoom={16}
        maxBounds={[110, 10, 132, 35]}
        initialViewState={{
          bounds: initialBounds,
          padding: initialPadding,
        }}
      />
      {children}
    </Map>
  );
}

function TaiwanMapFallback() {
  const { minX, minY, maxX, maxY } = MAIN_GROUP_BBOX;
  const width = maxX - minX;
  const height = maxY - minY;

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E8F0F8' }}>
      <Svg width="88%" height="78%" viewBox={`${minX - 18} ${minY - 18} ${width + 36} ${height + 36}`}>
        {taiwanIslands.map((island) => (
          <Path
            key={island.id}
            d={island.d}
            fill="#DCE6EF"
            stroke="#607C95"
            strokeWidth={island.id === 'taiwan' ? 3 : 1.4}
            strokeLinejoin="round"
          />
        ))}
      </Svg>
    </View>
  );
}
