import {
  Activity,
  AlertTriangle,
  Bike,
  Cloud,
  CupSoda,
  Dog,
  Droplets,
  Eye,
  Heart,
  Leaf,
  Locate,
  Map,
  Megaphone,
  Menu,
  Moon,
  Search,
  Settings,
  Shield,
  Shirt,
  Soup,
  Sprout,
  Store,
  Sun,
  Thermometer,
  User,
  Wind,
  X,
  type LucideProps,
} from 'lucide-react-native';
import type { WeatherIconName } from '@/types/weather';

const icons = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  bike: Bike,
  cloud: Cloud,
  'cup-soda': CupSoda,
  dog: Dog,
  droplets: Droplets,
  eye: Eye,
  heart: Heart,
  leaf: Leaf,
  locate: Locate,
  map: Map,
  megaphone: Megaphone,
  menu: Menu,
  moon: Moon,
  search: Search,
  settings: Settings,
  shield: Shield,
  shirt: Shirt,
  soup: Soup,
  sprout: Sprout,
  store: Store,
  sun: Sun,
  thermometer: Thermometer,
  user: User,
  wind: Wind,
  x: X,
} satisfies Record<WeatherIconName, React.ComponentType<LucideProps>>;

export function WeatherIcon({ name, ...props }: LucideProps & { name: WeatherIconName }) {
  const Icon = icons[name];
  return <Icon {...props} />;
}
